version: "3.9"

services:

  ##20000
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "dockerPass1!"
        ACCEPT_EULA: "Y"

networks:
  project:
    name: project